Partio: Partio::PartioSe Class Reference
Partio::PartioSe Class Reference
NOTE: This class is experimental and may be deleted/modified in future versions.
#include <PartioSe.h>
Public Types
typedef SeExpression::LocalVarTable::const_iterator LocalVarTableIterator
Public Member Functions
PartioSe (Partio::ParticlesDataMutable *parts, const char *expr)
PartioSe (Partio::ParticlesDataMutable *partsPairing, Partio::ParticlesDataMutable *parts, const char *expr)
void addSet (const char *prefix, Partio::ParticlesDataMutable *parts, int &setIndex)
void addExport (const std::string &name, LocalVarTableIterator it, Partio::ParticlesDataMutable *parts, int &setIndex)
virtual ~PartioSe ()
bool runAll ()
bool runRandom ()
void run (int i)
bool runRange (int istart, int iend)
void setTime (float val)
SeExprVarRef * resolveVar (const std::string &s) const
Private Types
typedef std::map< std::string, AttribVar< int > * > IntVarMap
typedef std::map< std::string, AttribVar< float > * > FloatVarMap
typedef std::vector< VarToPartio< int > * > IntVarToPartio
typedef std::vector< VarToPartio< float > * > FloatVarToPartio
Private Member Functions
PartioSe (const PartioSe &)
PartioSe & operator= (const PartioSe &)
Private Attributes
bool isPaired
int currentIndex
Partio::ParticleAttribute pairH1
Partio::ParticleAttribute pairH2
int pairIndex1
int pairIndex2
Partio::ParticlesDataMutable * parts
Partio::ParticlesDataMutable * partsPairing
IntVarMap intVars
FloatVarMap floatVars
IntVarToPartio intVarToPartio
FloatVarToPartio floatVarToPartio
SimpleVar indexVar
SimpleVar countVar
SimpleVar timeVar
Detailed Description
NOTE: This class is experimental and may be deleted/modified in future versions.
Member Typedef Documentation
typedef std::map<std::string,AttribVar<float>*> Partio::PartioSe::FloatVarMap private
typedef std::vector<VarToPartio<float>*> Partio::PartioSe::FloatVarToPartio private
typedef std::map<std::string,AttribVar<int>*> Partio::PartioSe::IntVarMap private
typedef std::vector<VarToPartio<int>*> Partio::PartioSe::IntVarToPartio private
typedef SeExpression::LocalVarTable::const_iterator Partio::PartioSe::LocalVarTableIterator
Constructor & Destructor Documentation
Partio::PartioSe::PartioSe (Partio::ParticlesDataMutable * parts, const char * expr)
References addExport(), addSet(), and currentIndex.
Partio::PartioSe::PartioSe (Partio::ParticlesDataMutable * partsPairing, Partio::ParticlesDataMutable * parts, const char * expr)
References addExport(), addSet(), Partio::ParticlesInfo::attributeInfo(), currentIndex, pairH1, pairH2, pairIndex1, and pairIndex2.
Partio::PartioSe::~PartioSe () virtual
References floatVars, floatVarToPartio, intVars, and intVarToPartio.
Partio::PartioSe::PartioSe (const PartioSe &) private
Member Function Documentation
void Partio::PartioSe::addExport (const std::string & name, LocalVarTableIterator it, Partio::ParticlesDataMutable * parts, int & setIndex)
References Partio::ParticlesInfo::attributeInfo(), Partio::FLOAT, floatVarToPartio, Partio::INDEXEDSTR, Partio::INT, intVarToPartio, Partio::ParticleAttribute::name, Partio::ParticleAttribute::type, and Partio::VECTOR.
Referenced by PartioSe().
void Partio::PartioSe::addSet (const char * prefix, Partio::ParticlesDataMutable * parts, int & setIndex)
References Partio::VarToPartio< T >::attr, Partio::ParticlesInfo::attributeInfo(), Partio::FLOAT, Partio::INDEXEDSTR, Partio::INT, Partio::ParticleAttribute::name, Partio::ParticlesInfo::numAttributes(), Partio::VarToPartio< T >::parts, Partio::ParticleAttribute::type, and Partio::VECTOR.
Referenced by PartioSe().
PartioSe& Partio::PartioSe::operator= (const PartioSe &) private
SeExprVarRef * Partio::PartioSe::resolveVar (const std::string & s) const
References countVar, floatVars, indexVar, intVars, and timeVar.
void Partio::PartioSe::run (int i)
References currentIndex, Partio::ParticlesData::data(), floatVarToPartio, indexVar, intVarToPartio, isPaired, Partio::ParticlesInfo::numParticles(), pairH1, pairH2, pairIndex1, pairIndex2, parts, partsPairing, and Partio::SimpleVar::val.
Referenced by runRandom(), and runRange().
bool Partio::PartioSe::runAll ()
References Partio::ParticlesInfo::numParticles(), parts, and runRange().
bool Partio::PartioSe::runRandom ()
References countVar, Partio::ParticlesInfo::numParticles(), parts, run(), and Partio::SimpleVar::val.
bool Partio::PartioSe::runRange (int istart, int iend)
References countVar, Partio::ParticlesInfo::numParticles(), parts, run(), and Partio::SimpleVar::val.
Referenced by runAll().
void Partio::PartioSe::setTime (float val)
References timeVar, and Partio::SimpleVar::val.
Member Data Documentation
SimpleVar Partio::PartioSe::countVar mutable private
Referenced by resolveVar(), runRandom(), and runRange().
int Partio::PartioSe::currentIndex private
Referenced by PartioSe(), and run().
FloatVarMap Partio::PartioSe::floatVars mutable private
Referenced by resolveVar(), and ~PartioSe().
FloatVarToPartio Partio::PartioSe::floatVarToPartio private
Referenced by addExport(), run(), and ~PartioSe().
SimpleVar Partio::PartioSe::indexVar mutable private
Referenced by resolveVar(), and run().
IntVarMap Partio::PartioSe::intVars mutable private
Referenced by resolveVar(), and ~PartioSe().
IntVarToPartio Partio::PartioSe::intVarToPartio private
Referenced by addExport(), run(), and ~PartioSe().
bool Partio::PartioSe::isPaired private
Referenced by run().
Partio::ParticleAttribute Partio::PartioSe::pairH1 private
Referenced by PartioSe(), and run().
Partio::ParticleAttribute Partio::PartioSe::pairH2 private
Referenced by PartioSe(), and run().
int Partio::PartioSe::pairIndex1 private
Referenced by PartioSe(), and run().
int Partio::PartioSe::pairIndex2 private
Referenced by PartioSe(), and run().
Partio::ParticlesDataMutable* Partio::PartioSe::parts private
Referenced by run(), runAll(), runRandom(), and runRange().
Partio::ParticlesDataMutable* Partio::PartioSe::partsPairing private
Referenced by run().
SimpleVar Partio::PartioSe::timeVar mutable private
Referenced by resolveVar(), and setTime().
The documentation for this class was generated from the following files:
/home/sean/partio/src/lib/PartioSe.h
/home/sean/partio/src/lib/PartioSe.cpp