Partio: Partio::ParticlesInfo Class Reference
Partio::ParticlesInfo Class Reference abstract
Particle Collection Interface.
#include <Partio.h>
Public Member Functions
virtual void release () const =0
virtual int numParticles () const =0
Number of particles in the structure.
virtual int numAttributes () const =0
Number of per-particle attributes.
virtual int numFixedAttributes () const =0
Number of fixed attributes.
virtual bool attributeInfo (const char *attributeName, ParticleAttribute &attribute) const =0
Lookup an attribute by name and store a handle to the attribute.
virtual bool fixedAttributeInfo (const char *attributeName, FixedAttribute &attribute) const =0
Lookup an attribute by name and store a handle to the attribute.
virtual bool attributeInfo (const int index, ParticleAttribute &attribute) const =0
Lookup an attribute by index and store a handle to the attribute.
virtual bool fixedAttributeInfo (const int index, FixedAttribute &attribute) const =0
Lookup an attribute by index and store a handle to the attribute.
Protected Member Functions
virtual ~ParticlesInfo ()
Friends
void freeCached (ParticlesData *particles)
Detailed Description
Particle Collection Interface.
This class provides ways of accessing basic information about particles, the number in the set, the attribute names and types, etc. No actual data can be read or written.
Constructor & Destructor Documentation
virtual Partio::ParticlesInfo::~ParticlesInfo () inline protected virtual
References attributeInfo(), fixedAttributeInfo(), freeCached, numAttributes(), numFixedAttributes(), numParticles(), and release().
Member Function Documentation
virtual bool Partio::ParticlesInfo::attributeInfo (const char * attributeName, ParticleAttribute & attribute) const pure virtual
Lookup an attribute by name and store a handle to the attribute.
Referenced by Partio::PartioSe::addExport(), Partio::PartioSe::addSet(), Partio::PartioSe::PartioSe(), and ~ParticlesInfo().
virtual bool Partio::ParticlesInfo::attributeInfo (const int index, ParticleAttribute & attribute) const pure virtual
Lookup an attribute by index and store a handle to the attribute.
virtual bool Partio::ParticlesInfo::fixedAttributeInfo (const char * attributeName, FixedAttribute & attribute) const pure virtual
Lookup an attribute by name and store a handle to the attribute.
Referenced by ~ParticlesInfo().
virtual bool Partio::ParticlesInfo::fixedAttributeInfo (const int index, FixedAttribute & attribute) const pure virtual
Lookup an attribute by index and store a handle to the attribute.
virtual int Partio::ParticlesInfo::numAttributes () const pure virtual
Number of per-particle attributes.
Referenced by Partio::PartioSe::addSet(), and ~ParticlesInfo().
virtual int Partio::ParticlesInfo::numFixedAttributes () const pure virtual
Number of fixed attributes.
Referenced by ~ParticlesInfo().
virtual int Partio::ParticlesInfo::numParticles () const pure virtual
Number of particles in the structure.
Referenced by Partio::PartioSe::run(), Partio::PartioSe::runAll(), Partio::PartioSe::runRandom(), Partio::PartioSe::runRange(), and ~ParticlesInfo().
virtual void Partio::ParticlesInfo::release () const pure virtual
Frees the memory if this particle set was created with create() or release() Reduces reference count if it was obtained with readCached() and if the ref count hits zero, frees the memory
Referenced by ~ParticlesInfo().
Friends And Related Function Documentation
void freeCached (ParticlesData * particles) friend
Referenced by ~ParticlesInfo().
The documentation for this class was generated from the following file:
/home/sean/partio/src/lib/Partio.h