Partio: Partio::Vec3 Class Reference
Partio::Vec3 Class Reference
#include <PartioVec3.h>
Public Member Functions
Vec3 ()
Vec3 (const float x, const float y, const float z)
Vec3 (const float v[3])
float length ()
float normalize ()
Vec3 normalized () const
Vec3 operator* (const float a) const
Vec3 operator- (const Vec3 &v) const
Vec3 operator+ (const Vec3 &v) const
Vec3 operator+= (const Vec3 &v)
Vec3 cross (const Vec3 &v) const
Vec3 min (const Vec3 &v) const
Vec3 max (const Vec3 &v) const
Public Attributes
float x
float y
float z
Constructor & Destructor Documentation
Partio::Vec3::Vec3 () inline
Referenced by max(), min(), operator*(), Partio::operator*(), operator+(), and operator-().
Partio::Vec3::Vec3 (const float x, const float y, const float z) inline
Partio::Vec3::Vec3 (const float v[3]) inline
Member Function Documentation
Vec3 Partio::Vec3::cross (const Vec3 & v) const inline
References x, y, and z.
float Partio::Vec3::length () inline
Referenced by normalize().
Vec3 Partio::Vec3::max (const Vec3 & v) const inline
References Vec3(), x, y, and z.
Vec3 Partio::Vec3::min (const Vec3 & v) const inline
References Vec3(), x, y, and z.
float Partio::Vec3::normalize () inline
References length().
Referenced by normalized().
Vec3 Partio::Vec3::normalized () const inline
References normalize().
Vec3 Partio::Vec3::operator* (const float a) const inline
References Vec3().
Vec3 Partio::Vec3::operator+ (const Vec3 & v) const inline
References Vec3(), x, y, and z.
Vec3 Partio::Vec3::operator+= (const Vec3 & v) inline
References x, y, and z.
Vec3 Partio::Vec3::operator- (const Vec3 & v) const inline
References Vec3(), x, y, and z.
Member Data Documentation
float Partio::Vec3::x
Referenced by cross(), max(), min(), Partio::operator*(), operator+(), operator+=(), operator-(), and Partio::operator<<().
float Partio::Vec3::y
Referenced by cross(), max(), min(), Partio::operator*(), operator+(), operator+=(), operator-(), and Partio::operator<<().
float Partio::Vec3::z
Referenced by cross(), max(), min(), Partio::operator*(), operator+(), operator+=(), operator-(), and Partio::operator<<().
The documentation for this class was generated from the following file:
/home/sean/partio/src/lib/PartioVec3.h